### ISSUE TITLE
Memory Leak Issues

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#13]
This seems to be an apple bug with @Published. I'm writing various workarounds to mitigate the problem and have filed a radar: https://github.com/winsmith/PublishedLeakDemo

**Comment by winsmith** [comment]
I'm keeping this issue open but won't work on it for a while, to collect more info. In the meantime, I'm sad to say I'll ask you to quit the app every now and then.

**Comment by winsmith** [comment]
Great news, recompiling the app with Xcode 13 greatly reduces the memory leak issue for me. I'll investigate further, but this is a really good sign.

**Comment by maxbaeumle** [comment]
475 still leaks a lot which adds up if you keep the application running over time .
<img width="539" alt="Bildschirmfoto 2021-11-08 um 11 11 04" src="https://user-images.githubusercontent.com/1935810/140723902-e3b6fbe6-27c9-4334-b22a-19f896ae5999.png">

**Comment by winsmith** [comment]
Is that on macOS 11 or 12? AFAIK the leak is 11 only... (please let it be 11)
