### ISSUE TITLE
Update Quickstart

### ISSUE THREAD

**Issue by vpukhanov** [TelemetryDeck/Viewer#167]
Hi! Not sure if this repo is the correct place to track website issues, but I recently went through the Quickstart, and it was a super smooth sailing 😎 . I've just noticed some typos and out of date instructions which I wanted to bring up to help polish it, hope this helps ❤️ 

https://telemetrydeck.com/pages/setting-up-your-application.html

`This concludes **are** the preparation` -> This concludes the preparation

`In the menu, select File -> Swift Packages -> Add Package Dependency....` -> In the new Xcode this is moved to `File -> Add Packages…`

`The TelemetryClient package will **give** provide you with a class` -> The TelemetryClient package will provide you with a class 

https://telemetrydeck.com/pages/sending-signals.html

`A string that indicates which kind of event **happend**` -> happened

`TelemetryManager will send signals **as** only` -> TelemetryManager will send signals only

`See **TelemetryClients** README.md` -> TelemetryClient's

**Comment by winsmith** [comment]
Thank you very much! I appreciate this a lot. I'll move this ticket into our website repo :)

**Comment by winsmith** [comment]
I fixed those real quick because I was working on the website anyway!
