### ISSUE TITLE
iOS: Drag and Drop to Reorder Insights

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#173]
Currently, it is not possible to reorder insights in iOS edit mode. Ideally, users should be able to use Drag and Drop to rearrange insights.

- [x] Side Quest: Try if its possible to change the "Edit" button to `square.and.pencil`
- [ ] Update EditorModeGroupEditor to allow reordering its items
- [ ] update all insights in the group in such a way that they are now ordered according to the user's wishes

# Links

https://www.hackingwithswift.com/quick-start/swiftui/how-to-enable-editing-on-a-list-using-editbutton

**Comment by BasO** [comment]
I suggest changing back the square.and.pencil button to an "Edit" button (which will automatically be the case with a native EditButton). My rationale is that the `square.and.pencil` icon is associated with creating a new entity (e.g. in Notes and Mail).
