### ISSUE TITLE
Add Insight to show real-time count of users in the app

### ISSUE THREAD

**Issue by RyanRamchandar** [TelemetryDeck/Viewer#189]
This can be bucketed by seconds, minute(s) but the idea is to get a real-time snapshot of your apps users in the moment.
A trailing line chart can show the history.

**Comment by winsmith** [comment]
Currently for the web dashboard only, the desktop app is undergoing some structural changes 

![Screen Shot 2022-02-16 at 16 50 54](https://user-images.githubusercontent.com/954120/154302544-937d8162-a523-429c-b268-498bd12359da.png)

**Comment by winsmith** [comment]
We're now reloading that thing every 5 minutes :) Last minute is not possible, alas because we're only storing signals with a granularity of one hour. This helps a lot with anonymization and performance
