### ISSUE TITLE
Nothing happens when pressing "Create an empty insight"

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#199]
When I add a new insight and in the insight choose select "Or create an empty insight" at the very bottom, nothing happens. I've tested with both Safari and Brave browsers, in both cases nothing happens. I do not have any content-blockers in Brave, so that shouldn't be the issue. Selecting any of the other entries works, but empty doesn't.

**Comment by winsmith** [comment]
Fixed 😊
