### ISSUE TITLE
Broken link from macOS app

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#208]
Opening Slack from the Telemetry macOS fails. It opens https://telemetrydeck.com/pages/slack.html and it is 404

**Comment by winsmith** [comment]
Thanks! This *should* redirect to http://telemetrydeck.com/slack/ ! I'll update this ticket when it's fixed.

**Comment by winsmith** [comment]
Things work now -- there was a broken redirect. Thank you very much :)
