### ISSUE TITLE
Dashboards don't work (anymore) but I can see Recent Signals

### ISSUE THREAD

**Issue by littlewolf-creativebits** [TelemetryDeck/Viewer#209]
In Recent Signals, I can see previously received signals and new signals that I send. But in Overview, Playground and Metrics the dashboards / queries show no data available for the any time period (that includes the signals). 

I'm in test mode (the signals were also sent in test mode). The dashboards worked correctly on Friday, but starting on Sunday (when i checked again) they failed to show any data.

![signals](https://user-images.githubusercontent.com/4115404/215412737-22a6e6bd-88fc-4940-a5c2-da51abbcca6f.png)
![dasboards](https://user-images.githubusercontent.com/4115404/215412763-0877771c-8be7-45ae-8602-f6ba197f51e8.png)

**Comment by winsmith** [comment]
Hi, thanks so much for submitting this. The reason for this behavior is most likely a bug in an update we pushed to the server on Saturday -- the update was about auto generating filters, and it might have broken test mode. 

I'm on it and will update this ticket when a fix is available.

**Comment by littlewolf-creativebits** [comment]
Thank you for the quick feedback!

**Comment by winsmith** [comment]
Hi, this bug has just been fixed. Please wait 5-10 minutes for it to reach the server and then give it a try. Again, thanks a lot for reporting it!
