### ISSUE TITLE
Custom query stopped working

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#210]
FYI: This custom query to show the max value of certain fields across all signals used to work, but now it doesn't work anymore. I have almost no experience with the query language.

```
{
  "aggregations": [
    {
      "fieldName": "categoriesCount",
      "name": "Max categories count",
      "type": "longMax"
    },
    {
      "fieldName": "activitiesCount",
      "name": "Max activitiesCount",
      "type": "longMax"
    },
    {
      "fieldName": "maxActivityCountPerCategory",
      "name": "Max maxActivityCountPerCategory",
      "type": "longMax"
    },
    {
      "fieldName": "highestExpenseAmount",
      "name": "Max expense",
      "type": "longMax"
    }
  ],
  "dataSource": "telemetry-signals",
  "filter": {
    "fields": [
      {
        "dimension": "appID",
        "type": "selector",
        "value": "appid removed"
      },
      {
        "dimension": "isTestMode",
        "type": "selector",
        "value": "false"
      },
      {
        "dimension": "type",
        "type": "selector",
        "value": "Scene active"
      }
    ],
    "type": "and"
  },
  "granularity": "all",
  "queryType": "groupBy"
}
```

**Comment by winsmith** [comment]
Thanks for the report! We changed the way queries are evaluated slightly, I'll check it out and tell you how to fix it :)

**Comment by winsmith** [comment]
Hi, I've fixed a couple of other bugs in query construction, and then came to your ticket. It seems to be fixed now. Can you check if this is the result you were expecting please? 

<img width="1044" alt="Screenshot 2023-02-05 at 14 18 26" src="https://user-images.githubusercontent.com/954120/216821252-61d7baba-5956-4788-9870-d62e883a978d.png">

**Comment by KaiOelfke** [comment]
It's still broken in my dashboard unfortunately.

**Comment by winsmith** [comment]
I think I found it now – there was a wrong hidden value in the database that caused the query to be evaluated as a time series even though it should have been evaluated as a custom query. I'll push an update to the server shortly.

**Comment by winsmith** [comment]
The fix is now on the server, and I checked that your insight now shows data! Thanks a lot for reporting this!
