### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by DanielStormApps** [TelemetryDeck/Viewer#215]
Insight ID: 207F8BAC-80B3-4209-885B-AEFCE917470E

Summary:
- Not displaying as a pie chart.
- I believe this was a custom query prior to the latest update.

Environment:
- Safari Version 16.3 (18614.4.6.1.6)

Generated query:
```
{
  "aggregations": [
    {
      "fieldName": "clientUser",
      "name": "count",
      "type": "thetaSketch"
    }
  ],
  "appID": "my_awesome_app_id",
  "baseFilters": "thisApp",
  "dataSource": "telemetry-signals",
  "dimension": {
    "dimension": "locale",
    "outputName": "locale",
    "type": "default"
  },
  "granularity": "month",
  "metric": {
    "metric": "count",
    "type": "numeric"
  },
  "queryType": "topN",
  "threshold": 200
}
```

<img width="1080" alt="pie chart locale issue" src="https://user-images.githubusercontent.com/10573489/222765981-d03e3feb-9363-4bc8-bff1-7c4853a6e29b.png">

**Comment by winsmith** [comment]
Thanks for the issue! This is a new feature: you set your granularity to "month" so, we're choosing a representation that can show you the monthly breakdown of locales. Set the granularity to "all" to get a pie chart

**Comment by winsmith** [comment]
> I believe this was a custom query prior to the latest update.

I'll have a look in the database, maybe there's a display bug there.

**Comment by DanielStormApps** [comment]
> Thanks for the issue! This is a new feature: you set your granularity to "month" so, we're choosing a representation that can show you the monthly breakdown of locales. Set the granularity to "all" to get a pie chart

That did the trick. Thank you!

**Comment by winsmith** [comment]
I did check out the insight in the DB and didn't find anything weird going on –– I'll keep an eye on it if this problem comes up again.

If you want to convert the insight to a custom query again, it should be fine to just click the respective button again.
