### ISSUE TITLE
Insight Editor UX: Finding actions require extra step (hidden in dropdown)

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#221]
![Bildschirm­foto 2023-03-21 um 10 05 39](https://user-images.githubusercontent.com/6942160/226560816-0366795e-23e5-4529-b9f4-633e2b6c02e3.png)

I wanted to delete an insight and wondered where the delete button is. I figured out that the buttons are hidden behind the "Actions" dropdown a few seconds later than necessary. I think there's no need for a dropdown if there are only 2 actions anyway. Maybe you're planning to add more actions later, but I think up to 3 actions don't require a dropdown. At least not on desktop/iPad size screens. And even if you had more than 3 actions, I personally would appreciate if the most common actions would be shown directly and only less common actions were hidden in a 'More Actions' dropdown.

**Comment by winsmith** [comment]
This is where "move" and "duplicate" will live 😎
