### ISSUE TITLE
Insight Editor UX: 'and' and 'or' wording confusing

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#222]
![Bildschirm­foto 2023-03-21 um 10 07 10](https://user-images.githubusercontent.com/6942160/226561310-918684d7-c45c-48d3-82fc-4c4ff3d5d576.png)

When I looked at this list of potential filter types, I had to re-read the last two at least 3 times until I understood the right emphasis for it to make sense. At first I thought you forgot to add a word before the 'and' and 'or' and tried to guess what that word could be. To solve this, I recommend putting the words 'and' and 'or' in quotes as I do here. Alternatively, you could also make them all uppercase like in AND and OR. Or both.

P.S. This issue reminds me 
![Bildschirmfoto 2023-03-20 um 22 41 07](https://user-images.githubusercontent.com/6942160/226562032-120676f5-5f3e-416c-8d11-bbbe74f7b54a.jpeg)
of this quiz question: 😂

**Comment by winsmith** [comment]
Hahaha thanks! (btw I'm in the audience for the wer wird Millionär show that broadcasts on 09.04.2023 if you're watching, back row on the left)

**Comment by winsmith** [comment]
Deploying this:

<img width="470" alt="Screenshot 2023-03-29 at 17 05 19" src="https://user-images.githubusercontent.com/954120/228582833-51b8ac55-8b79-4d43-b734-fa376676e8c0.png">
