### ISSUE TITLE
Insight Editor Funnels: Repeating signal type not working as expected

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#225]
![Bildschirm­foto 2023-03-21 um 10 43 15](https://user-images.githubusercontent.com/6942160/226568939-4484f6d4-ba64-4722-874c-f97ea75bab7f.png)

I've set up a first funnel for my Onboarding and noticed a weird behavior: I have an app where users can add translations to their apps. I want to know how many of my users actually get to the state of actually using my app. I expect more users to at least try out the main workflow of the app once to see how it works than to actually use the app. But to differentiate those who just "try it out once" from those who "actually use it for their app", I want to check if the a signal type in the funnel happens at least at 3 distinct times. I thought by simply adding the signal condition in 3 different steps it would work, but it's showing that 100% of my users who did the action one time also did it a second and third time, which is extremely unlikely.

So I believe that this feature doesn't work yet, or at least not the way I set it up. Could you please point me to the right direction (or add the feature)? Thanks!

**Comment by winsmith** [comment]
Funnel steps work as intersections between the groups of users who fulfill a step and all the previous steps. Since the intersection of a group with itself is the group, you're ending up with this behavior. It's currently not possible to do what you're trying to do here, this is an implementation limitation.

I think it'd be easiest for you to determine the condition "has visited this screen three times or more" in code and then send a specific signal for that. E

**Comment by Jeehut** [comment]
@winsmith Alright, thanks for explaining the limitation, I'll implement it in code then! 👍

**Comment by Jeehut** [comment]
Having that said, I noticed a weird behavior in some of my funnels where I have an action that only triggers on first app start: If I moved the step with the "firstAppStart" from the first place to another one, e.g. after "present paywall" which definitely gets triggered at a later time, I would expect the funnel to drop from 100% to 0% because no user will first trigger "present paywall" and then later "first app start", but it wasn't 0%, which was confusing. Do I understand it right that the timing of when the signal type was sent is not important? It's just checking "if" it was sent (within the specified granularity)?

Also, how does the grouping with the "Granularity" field happen, e.g. when I specify "hour", will it group all from 14:00 to 14:59 into one group or will it go back 1 hour from the current date, e.g. 13:16 to 14:16?

**Comment by winsmith** [comment]
You're correct that the order does actually not matter, just that a user is both in the "step 1" and the "step 2" group. 

Granularity grouping works with global buckets, i.e. a day is always from 00:00 to 23:59 UTC, and an hour is always from 14:00 to 14:59. This is so you can e.g. compare how your funnel values compare from this week to the last week.
