### ISSUE TITLE
Insight Editor UX: Unclear that step names are editable

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#227]
After reporting https://github.com/TelemetryDeck/Issues/issues/226 and going back to the overview where I saw the graph of my funnel with step names "Step 1", "Step 2", etc. I really wished I could rename the steps. Then, because I remembered that also search works although it's not obvious that it's possible, I tried clicking into the label of "Step 1" in the editor – and again, it worked!

![Bildschirm­foto 2023-03-21 um 11 00 12](https://user-images.githubusercontent.com/6942160/226573142-f5757cb5-169c-4e2a-9b9c-bd9142548587.png)

While this is great, that's yet another discoverability problem. I would have never guessed that these are editable text fields, because they are lacking any sign of being a text field. To indicate that they are editable, I suggest changing the background color of the text field to be a bit darker or brighter than the rest of the colored background where the text field is included. Additionally, you might want to add a thin gray border, too. See for example how the GitHub issue editor I am currently typing into makes clear that the title is a text field by using (a) a different background shade and (b) a thin border:

![Bildschirm­foto 2023-03-21 um 11 03 52](https://user-images.githubusercontent.com/6942160/226573949-778c0d63-1334-4de9-9b7f-453a2e5cb070.png)

**Comment by winsmith** [comment]
I really appreciate all your issue reports! Thank you very much!
