### ISSUE TITLE
Feature Request: Duplicate insight button

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#228]
I just set up my first funnel and I'd like to create different variants of it, where the first few steps are the same, but I want to analyze different paths my users go on first app usage. As creating funnels involves investing some time, it would be great if I could simply "Duplicate" an entire insight, give it a different name and edit it from there. This would save a lot of time.

**Comment by winsmith** [comment]
Thanks! We already have a feature for "duplicate insight" so I'm closing the other one and leaving this one open.

**Comment by winsmith** [comment]
It is done.

**Comment by Jeehut** [comment]
Thank you! 🚀
