### ISSUE TITLE
Auto Scroll up when switching views

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#234]
> When you are editing an insight in a group with many insights, the page refreshes to the editing mode, but retains the scroll position from the group page.
> 
> So if you have a group with lot’s of insights, the page reloads to a blank page, which gives the impression the page is still loading. Only when you scroll up, do you see the page actually loaded, and the editing controls were just not visible.
> 
> Would be nice if there was a programmatic scroll when going in to edit an insight, so you don’t need to manually scroll up to find the info.

**Comment by mikakruschel** [comment]
I think this was recently fixed. 👍

**Comment by winsmith** [comment]
I didn't fix it yet :D~ sorry.
