### ISSUE TITLE
Can't rename an app

### ISSUE THREAD

**Issue by alexstaravoitau** [TelemetryDeck/Viewer#235]
Perhaps I'm missing something obvious, but is there a way to rename your app in TelemetryDeck? I assumed there would be an option in _Settings_ -> _App Settings_, but the only setting there is a button to delete the app.

**Comment by winsmith** [comment]
This is actually not possible, thanks for reporting! We'll add that soon, but in the meantime, email daniel@telemetrydeck.com with the App ID, and the new desired name, and I'll rename it for you!
