### ISSUE TITLE
Insight Editor Saving Issues

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#236]
I'm having an issue while editing an insiqht.

Insight ID: 371B712F-1AFD-49FF-9B66-6C28181513FA

When I duplicate an insight, the duplicated insight behaves weirdly. For example, when I change the title, it doesn't save on first try. I have to do it a second time to change it. Or when I edit the value of a filter, it doesn't save, instead it creates a new filter but keeps the old and combines them automatically. Even if I explicitly delete the old, it won't save. It's weird.

**Comment by winsmith** [comment]
Thanks for reporting, the root cause for this is probably the same as https://github.com/TelemetryDeck/Issues/issues/217, i.e. you can somehow either change metadata or actual data, because they are managed by different components and there's a sync issue.

**Comment by winsmith** [comment]
To Do: 

- [ ] Write various tests for InsightEditor to make sure it continues working as expected
- [ ] Explicitly test duplicating insights
- [ ] Update InsightEditor to return not the full model but only updated keys and values
- [ ] Update InsightEditor to no longer track values internally but always display the values passed in from the outside
- [ ] Use the controller's delayedSave method to save the insight
