### ISSUE TITLE
Table too wide in overview of insights – values not visible

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#237]
I'm having an issue while editing an insiqht.

Insight ID: 876E3E9F-AE0E-4A93-92BD-CDA3EFB09147

When I set an insight to "table" mode, it doesn't show the values when looking at it from the list. It seems like it's rendering the outside in "compact" mode but the inside of the insight in "full width" mode. It should render in compact mode like expected.

By the way, it would also be great to see percentages in the table mode like in the pie chart mode.
![Bildschirmfoto 2023-04-28 um 08 42 48](https://user-images.githubusercontent.com/6942160/235073844-b89bb770-3a1b-4787-8305-ff3677ffd1d6.png)

**Comment by winsmith** [comment]
I've opened a separate issue for percentage based tables: https://github.com/TelemetryDeck/Issues/issues/251
