### ISSUE TITLE
Insights editor UX issues

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#248]
- I need to scroll to the bottom to create a new insight instead of having also a button at the top
- After scrolling down a lot (depending on how many insights I have in a group) and then completing the add new insight dialog I see a blank page, because my view port is still scrolled down. So I always have to scroll up a lot to see the actual insight editor. New users would think something went wrong with the empty page.
- The insights editor also shouldn't have a huge scrollable view port, if there's no UI needing that space

All this is with Firefox 112.0.2 on macOS 13.3.1

This screenshot shows what I see after completing the dialog. To see the editor I have to scroll to the top.
<img width="703" alt="Bildschirmfoto 2023-05-12 um 10 51 08" src="https://github.com/TelemetryDeck/Issues/assets/1190948/8f14453f-a080-4104-a4ae-2b838ff42e2b">

**Comment by winsmith** [comment]
Thanks for submitting this! This is a duplicate so I'm closing it but watch #234 for updates!
