### ISSUE TITLE
Custom Query Editor not accessible in Safari

### ISSUE THREAD

**Issue by davidkroeg** [TelemetryDeck/Viewer#254]
I'm having an issue while editing an insiqht.

Insight ID: E8DAF869-54DF-42D9-ACDE-C4D8E329EB89

When I try to edit a custom query in Safari the edit window for the JSON seems to be empty and not selectable. In Firefox I can edit them as usual. 

Safari Version: 16.3

**Comment by winsmith** [comment]
Thanks for the report. While I investigate, do you have any extensions active that might block web content? Or could you send me your Javascript Logs when loading the page? 

The reason I'm asking is that I use Safari as my main browser, and I've never seen the JSON editor not work, so I'm trying to find the specific circumstances that might make it break.

**Comment by winsmith** [comment]
I'm sorry but I can't reproduce the issue.
