### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by alexstaravoitau** [TelemetryDeck/Viewer#255]
I'm having an issue while viewing/editing an insiqht.

Insight ID: 9D51DC22-EE11-4C9C-ABFC-3D1A9D07AC40

Table view no longer displays property values in the left column (counts are correctly displayed on the right).

**Comment by winsmith** [comment]
Thanks for reporting, I'll have a look!

**Comment by winsmith** [comment]
Found it: the new code to try and find horizontal header rows was confused by the dot in your dimension name. Fixed and uploaded.

**Comment by alexstaravoitau** [comment]
Wow that was quick — thanks @winsmith 😇
