### ISSUE TITLE
Overview for a website using the JavascriptSDK with anonymous users is mostly useless

### ISSUE THREAD

**Issue by Timac** [TelemetryDeck/Viewer#259]
I added the JavascriptSDK to use anonymous users on my website. When I open the Overview on the Dashboard, I see the following:

<img width="1154" alt="Dashboard" src="https://github.com/TelemetryDeck/Issues/assets/738543/b96553d1-822e-474a-ac30-812c9c03fd18">

Note that I got 240 signals from anonymous users. The graphs displayed on the dashboard are:

- `Daily Active Users`: 1 user
- `Users in the last hour`: 1 user
- `Total users`: 1 user

=> The dashboard should be smart enough to display daily signals instead of daily users since all the users are anonymous.

- `App Versions` is empty
- `System Versions` displays 100%

=> Since I use the JavascriptSDK, I would expect to see the browser versions and System Versions

**Comment by winsmith** [comment]
I assume you switched to the web SDK in the meantime :)
