### ISSUE TITLE
Daily Signals

### ISSUE THREAD

**Issue by Timac** [TelemetryDeck/Viewer#266]
- I use the Javascript SDK on a website with anonymous users
- I would like to display a line chart where I see the daily number of signals
- When I create a Time Series with a daily granularity, I see a line between 2 days which is not was I would expect. 

<img width="915" alt="DailySignals" src="https://github.com/TelemetryDeck/Issues/assets/738543/4be0b975-d8de-4f49-8d5e-2590c83bea90">

**Comment by winsmith** [comment]
This insight is correct but the app seems to be configured to only show a single day, so that's just two data points to display. Please set the date range to something like 30 days in the left sidebar.

**Comment by Timac** [comment]
Ah you are right. Maybe you should make the popup menu in the left sidebar more prominent because I did not see it until now 😅
