### ISSUE TITLE
visionOS 1.0 is displayed as iOS 1.0

### ISSUE THREAD

**Issue by martinlexow** [TelemetryDeck/Viewer#267]
At least I’m pretty sure my app isn’t compatible with iOS 1.0 🙃
<img width="467" alt="Screenshot 2023-06-23 at 16 17 21" src="https://github.com/TelemetryDeck/Issues/assets/42469550/97c9e9f8-28ca-4b17-8513-5ea49e581036">

**Comment by winsmith** [comment]
Turns out `#if os(iOS)` evaluates to true under visionOS! Pushing a new version of the SDK soon!
