### ISSUE TITLE
Insight Editor Suggestion: Colours

### ISSUE THREAD

**Issue by mikesax** [TelemetryDeck/Viewer#278]
In the iOS versions, it would be very nice if the major versions could be one colour, and the subversions a tint of that colour. For example, 16.1 would be very light blue, 16.2 light blue, 16.3 dark blue, 15.0 medium red, etc.

This would also be a great thing to extend to other insights: a main category, and a subcategory. For example, in my meditations I have a topic and a category. If all the meditations of one category could be one main colour and the subtopics within that category be a shade of that colour, that would be amazing!

**Comment by winsmith** [comment]
Thanks Mike!
