### ISSUE TITLE
Show the name of the day when hovering over graphs

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#280]
<img width="300" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/9ff87c9e-df4e-4530-8f90-ddda8f3ea6a7">

Right now it's hard to find for example the last saturday in a graph.

**Comment by jordibruin** [comment]
Any updates on this? This is something I run into every day with almost all graphs.

**Comment by winsmith** [comment]
Fixed in https://github.com/TelemetryDeck/web/pull/1692

Thanks for the reminder Jordi :)
