### ISSUE TITLE
Issue showing graphs in iOS app

### ISSUE THREAD

**Issue by mpdifran** [TelemetryDeck/Viewer#281]
I've loaded my project in the iOS app, but all the graphs look like this (see screenshot). 
![image](https://github.com/TelemetryDeck/Issues/assets/1365987/4f6f295f-09e7-460a-a8fa-790dafed540e)

**Comment by winsmith** [comment]
I'm sorry, right now the iOS and macOS apps are completely unsupported. I don't have the time to keep up with developing them and the main application. If you're interested, the app is open source and you can add support for newer chart types yourself. :)
