### ISSUE TITLE
Add % conversion rate for each funnel step

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#282]
The funnel insights currently show the total percentage at each step like 100%, 30%, 15%, 10%, but it'd be nice to see how much is lost at each step to see which step to optimize. In this example it would be 70% loss, 50% loss, 33,4% loss so the first step has the most potential.

**Comment by winsmith** [comment]
Nice idea! I'll add it to the board, thanks for requesting it!
