### ISSUE TITLE
Dashboard showing incorrect website data

### ISSUE THREAD

**Issue by haIIux** [TelemetryDeck/Viewer#283]
As shown in the picture, there is populated data for a website called OpenBytes. While I have OpenBytes as a TelemetryDeck project within this account, I am not viewing this site. I have confirmed that the app id's are different between the two sites, and that I am using the correct one.

<img width="1429" alt="Screenshot 2023-08-15 at 21 57 13" src="https://github.com/TelemetryDeck/WebSDK/assets/47156971/aab4a7c4-6daa-4fda-b2d1-e2143180bad3">

**Comment by winsmith** [comment]
Thanks for reporting! This seems serious, and I have an idea where the problem might lie.

**Comment by winsmith** [comment]
I found the problem. Our filtering system defaults to "include all apps in this organization" when running a custom query (which these views are behind the scenes). So I've changed the queries baseFilter properties to "thisApp" and it seems to work correctly now.
