### ISSUE TITLE
WebSDK: src parameter not included in web dashboard "combinedSource"

### ISSUE THREAD

**Issue by conath** [TelemetryDeck/Viewer#284]
Version 1.0.0 of WebSDK, but I believe the issue is server-side:

If I browse to the URL: `https://kirchplatz-giesing.de/?src=testing` where the WebSDK is included, I expect the parameter value `testing` to appear in the TelemetryDeck web dashboard under combinedSource.

Problem: `none` is shown in combinedSource in the dashboard.

Workaround: use `source` parameter instead of `src`.

**Comment by winsmith** [comment]
Thanks for this issue. I updated our ingest servers so that they'll also include the src parameter in combinedSource. I'm sorry to say that this will not affect previous signals, but going forward this should work.
