### ISSUE TITLE
Improvement: Hiding empty entries from the graph overlay

### ISSUE THREAD

**Issue by jeremieb** [TelemetryDeck/Viewer#285]
It would look better without all the item with no result for the selected time.

<img width="1728" alt="Screen Shot 2023-08-29 at 11 10 32 AM" src="https://github.com/TelemetryDeck/Issues/assets/736246/932b94dc-4a64-40c4-aeec-2b51c4e910ba">

**Comment by winsmith** [comment]
Closing this a a duplicate of https://github.com/TelemetryDeck/Issues/issues/293
