### ISSUE TITLE
Funnel chart numbers changed by factor 50x over night

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#287]
Was there any calculation change for funnel charts? The numbers are suddenly drastically different without any change on my side.

**Comment by KaiOelfke** [comment]
<img width="1147" alt="Bildschirmfoto 2023-09-02 um 10 31 53" src="https://github.com/TelemetryDeck/Issues/assets/1190948/72251573-aec2-4546-b94a-9885f67b9b45">

Also the colors don't match. This makes it very confusing.

**Comment by KaiOelfke** [comment]
Okay so recreating the funnel chart from scratch shows different data (the old normal expected data). So it seems my old funnel insights corrupted overnight.

**Comment by winsmith** [comment]
This is concerning. I'll look into it, thanks!
