### ISSUE TITLE
Chart labels truncated

### ISSUE THREAD

**Issue by KaiOelfke** [TelemetryDeck/Viewer#292]
<img width="382" alt="Bildschirmfoto 2023-09-16 um 14 08 50" src="https://github.com/TelemetryDeck/Issues/assets/1190948/ab9b5f39-6201-4720-a033-9cffd5219017">

The version string is truncated.

**Comment by winsmith** [comment]
I improved this slightly by allowing the labels to angle more if necessary, but it will still occur when the card gets squeezed too much. I'll revisit the layout of this section and try out if it looks better with just two cards in a row instead of three.
