### ISSUE TITLE
Don't show values that are 0 when hovering on graphs

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#293]
<img width="317" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/0fe6074c-80f8-446d-9a7a-59edf379a438">

It makes it harder to read the values while hovering over a graph if also all the keys with value "0" are shown.

**Comment by jordibruin** [comment]
Any updates on this? This is something I run into every day with almost all graphs.

**Comment by winsmith** [comment]
Fixed in https://github.com/TelemetryDeck/web/pull/1692
