### ISSUE TITLE
Insight Editor too narrow, cuts off the end of payload key names

### ISSUE THREAD

**Issue by spongefile** [TelemetryDeck/Viewer#294]
I'm having an issue while editing an insiqht.

Insight ID: 1D2C18FC-2236-42CA-8C8F-16A3473DF0CB

The edit condition menu is too narrow to show the payload key names fully, cutting the ends of them off and making them indistinguishable from each other.

<img width="574" alt="CleanShot 2023-09-27 at 10 51 17@2x" src="https://github.com/TelemetryDeck/Issues/assets/1905464/0c186ec0-bfdb-459a-9653-3decf8f4f123">

**Comment by winsmith** [comment]
This is fixed for now, because I reverted the dropdown to a regular, OS based dropdown.
