### ISSUE TITLE
"Wrap in" not working for an "inner" element

### ISSUE THREAD

**Issue by nighthawk** [TelemetryDeck/Viewer#301]
I'm having an issue while editing an insiqht. I want to have a filter condition that is `a == "A" and (not b == "B")`. 

I cannot create it through the web editor if I built it top-down by first building `a == "A" and b == "B"` and then try to wrap the second statement in a not. I pick the context option and it just does nothing.

I *can* build it, if I build it bottom-up by starting with `b == "B"`, wrapping that in a not, and then wrapping that in an "and".

<img width="337" alt="Screenshot 2023-10-11 at 11 30 17" src="https://github.com/TelemetryDeck/Issues/assets/22646/bcf42738-7eb4-43b3-b1f0-0034865b46c3">

Insight ID: 967BF623-461F-4D2C-8566-377C6ED3ECB2

**Comment by winsmith** [comment]
Hi, I think this should now be fixed. Can you try again please?

**Comment by nighthawk** [comment]
Confirmed fixed. Thank you!
