### ISSUE TITLE
Insight Editor Issue - "Error: Abort.400: Serialized response context exceeds the max size[7168]: undefined - Updated"

### ISSUE THREAD

**Issue by DanielStormApps** [TelemetryDeck/Viewer#311]
An existing insight is no longer working.

Insight ID: 2CEF3B10-6F77-45EB-B11D-3310AEC0BAAF

Error displayed: `Error: Abort.400: Serialized response context exceeds the max size[7168]: undefined - Updated`

![Insight ID: 2CEF3B10-6F77-45EB-B11D-3310AEC0BAAF](https://github.com/TelemetryDeck/Issues/assets/10573489/7bcefd82-a813-4ff3-9a61-04f8eec82eb1)

**Comment by winsmith** [comment]
Sorry about that – we had issues with the calculation servers. Should be fixed.
