### ISSUE TITLE
Cannot Edit A/B Tests

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#317]
>  we have a bunch of A/B test insights with a variety of filters. As of a day or two ago when we go to edit them it shows blank filters (so we can't edit), even though the data is correctly being filtered.
> 
> If we convert to custom it appears the parameters are still present in the TQL. Any thoughts?

**Comment by martinhoeller** [comment]
Just wanted to report the same issue. Here is a screenshot of the editor view, in case it helps.

<img width="1217" alt="Screenshot 2023-11-16 at 08 43 41" src="https://github.com/TelemetryDeck/Issues/assets/5726765/b2b52535-7215-49ae-9570-cd3fdc539275">
