### ISSUE TITLE
Signal types dropdown doesn't update with more recent Signal types

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/Viewer#326]
I noticed this a few days ago but thought that the update may take time (like updates over night), but it's been a while since I have the for example "OptionsWizard.showPaywall" signals in my app but they still don't appear in the list of Signal types to choose from, which is a bummer. And the list still is not sorted alphabetically, which makes it really hard to find the ones I'm looking for.

As a workaround, I am now adding a random Signal type and then when I press edit, it's a plain text field where I can put my signal type. But this is really inconvenient as I have to look up the name of the signal type in my app and remember that I have that signal in the first place. Would be great if this was fixed soon!

Screenshots confirming the lack of the signal in the list and its existence in "Recent Signals":
<img width="625" alt="Bildschirmfoto 2023-12-14 um 11 32 46" src="https://github.com/TelemetryDeck/Issues/assets/6942160/2b321844-26f7-4be9-a253-5317aa12029a">
<img width="1130" alt="Bildschirmfoto 2023-12-14 um 11 33 44" src="https://github.com/TelemetryDeck/Issues/assets/6942160/6dac4962-c561-4895-8f60-79c8c70fbd9b">

**Comment by mbuchetics** [comment]
I have the same issue. In my case I created a new project and one of the signals are shown in the dropdown or the "signal type list".

**Comment by Jeehut** [comment]
<img width="1286" alt="Bildschirmfoto 2024-09-10 um 18 47 11" src="https://github.com/user-attachments/assets/4d4b7bc5-2c64-44ba-af61-5a1938532776">

I think this issue has been addressed with the introduction of the "Invalidate Cache and refresh Lexicon" button in the "Explore" tab on the right. Closing as no longer a direct problem for me.
