### ISSUE TITLE
Insight Editor Issue: custom date range in the past

### ISSUE THREAD

**Issue by jaanus** [TelemetryDeck/Viewer#328]
I'm having an issue while editing an insight.

I am looking at previous periods of my app.

I would like to simply specify a custom weekly date range like “Sep 4-10, 2023”. And then navigate the weeks back and forth. The custom range picker has some weird date controls that don’t let me do this.

**Comment by winsmith** [comment]
Hi, thanks for reporting this. I'm merging this with https://github.com/TelemetryDeck/Issues/issues/334
