### ISSUE TITLE
Data Wrong Format Error (Insight Editor Issue)

### ISSUE THREAD

**Issue by kmatzka** [TelemetryDeck/Viewer#329]
I'm having an issue.
Insight ID: 3A298471-3C57-4A81-8953-2B73F3AF3702

One of my insights shows this error:
_Error: The operation could not be completed. The data isn’t in the correct format.: undefined - Updated vor 3 Tagen_

Since I have not changed any line of code in my app, nor did I change the insight, this must be an issue with TelemetryDeck.
The signal **rehearsal.playButtonTapped** in my app **Script Buddy** is creating this issue.

Could you please have a look. 
Thanks,
Klaus.

**Comment by winsmith** [comment]
Thanks a lot for reporting this. I just pushed a possible fix, could you double check it's working now please ?

**Comment by kmatzka** [comment]
Thanks.
Data started to show up again a few days ago. History looks a bit patchy, though. Have a look at the png attached.

<img width="584" alt="playButtonTapped" src="https://github.com/TelemetryDeck/Issues/assets/43829400/b39b5e4d-2cc3-42ac-9210-6f792b0d0ffe">

**Comment by winsmith** [comment]
Thanks. This is because the server is returning `null` instead of `0` on these dates, but I see that this is not very helpful here. I'll close this ticket and figure something out for the `null` values in a separate ticket.
