### ISSUE TITLE
Null Values break various Charts

### ISSUE THREAD

**Issue by zakray** [TelemetryDeck/Viewer#331]
I'm having an issue while editing an insiqht.

Insight ID: EE1CAE4C-C7A4-4C3D-B00C-8BF8E3A3440E

Hi! I'm not sure why it's saying the data is in the wrong format, nothing's changed on my end.

**Comment by winsmith** [comment]
This looks like the result of a server change where the server is returning slightly different data. Thanks a lot for reporting! 

For posterity, example query:

```
{
  "filter": {
    "type": "or",
    "fields": [
      {
        "type": "selector",
        "value": "request-load",
        "dimension": "type"
      },
      {
        "type": "selector",
        "value": "calculation-successful",
        "dimension": "type"
      }
    ]
  },
  "queryType": "timeseries",
  "granularity": "month"
}
```

Errors occur in these display modes:

- [x] playground
- [x] raw
- [x] barChart
- [x] lineChart
- [x] funnelChart

**Comment by winsmith** [comment]
I've deployed a fix and things should work again. Could you double check and confirm please?
