### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by wonderbit** [TelemetryDeck/Viewer#333]
I'm having an issue while editing an insiqht.

Insight ID: 2AB693C3-225B-4E6B-A93C-D3DA406603BF

If I set my insight to count users it works but if I count signals I get an error:
"Error: The operation could not be completed. The data isn’t in the correct format.: undefined"

**Comment by winsmith** [comment]
Thanks for reporting this. I believe we fixed the issue, could you double check please?
