### ISSUE TITLE
Insight Issue: Duplicate values due to whitespace replaced with underscore

### ISSUE THREAD

**Issue by DanielStormApps** [TelemetryDeck/Viewer#340]
Values with whitespaces are having their whitespaces replaced with underscores, `_`.
This is resulting in double the values as `iOS 17` and `iOS_17` are unique from one another, see screenshot.
This is occurring across all values, not just `majorSystemVersion`, which results in inaccurate data across all insights.

Insight ID: CA9B1C72-0492-4A92-8A10-2B20430D3CE8

```
{
  "aggregations": [
    {
      "fieldName": "clientUser",
      "name": "count",
      "type": "thetaSketch"
    }
  ],
  "baseFilters": "thisOrganization",
  "dimension": {
    "dimension": "majorSystemVersion",
    "outputName": "majorSystemVersion",
    "type": "default"
  },
  "granularity": "all",
  "metric": {
    "metric": "count",
    "type": "numeric"
  },
  "queryType": "topN",
  "threshold": 200
}
```

![double-the-values](https://github.com/TelemetryDeck/Issues/assets/10573489/9fc2695c-a763-4900-a220-6a5b3eac900d)

**Comment by Cykelero** [comment]
Yikes, that's pretty serious. I really hope they'll be able to fix data retroactively.

**Comment by winsmith** [comment]
They were able to, for systemVersions and all other default keys :)
