### ISSUE TITLE
macOS stats sometimes split major versions

### ISSUE THREAD

**Issue by Cykelero** [TelemetryDeck/Viewer#341]
Looking at my major version stats today, I noticed that TelemetryDeck splits macOS 14 in two groups: `macOS 14` and `macOS_14`. These should of course be a single group; this makes it harder to visualize the version split.

![2024-01-26 12 44 41 Safari app (Retcon | TelemetryDeck)](https://github.com/TelemetryDeck/Issues/assets/2979318/c6d3b0fa-92d5-4173-a5a7-c6cb126afc4a)

**Comment by DanielStormApps** [comment]
Related: https://github.com/TelemetryDeck/Issues/issues/340#issue-2094235278

**Comment by winsmith** [comment]
Thanks this was a server issue that I hopefully fixed now.
