### ISSUE TITLE
Event Names Changed

### ISSUE THREAD

**Issue by VenanceCassens** [TelemetryDeck/Viewer#343]
I'm having an issue with ALL insights.

Insight ID: 8FBF2F8E-AD93-48E1-B5C1-AC063DCCEA7E

Since the overall failure was fixed, all new events have dashes instead of spaces in their names.
Thus, the tool considers these events as different events and none of my dashboards is as useful as before.

**Comment by DanielStormApps** [comment]
Related: https://github.com/TelemetryDeck/Issues/issues/340#issue-2094235278

**Comment by winsmith** [comment]
Sorry about that, it shouldnt happen again, but parts of your data might be slightly broken. I fixed what I could.
