### ISSUE TITLE
New Signal Types Not Showing Up

### ISSUE THREAD

**Issue by robertlong** [TelemetryDeck/Viewer#348]
Just started working with Telemetry Deck today. I tested my app in test mode, got everything showing up in the recent signals list. Then I went to create a funnel and my signals weren't available there. I then switched off test mode, tested my iOS App and there wasn't any recent signals list. I figured maybe this was because I was running a debug build. Tried again in release and now the recent signals show up, but I only see one entry under signal types.

![Screenshot 2024-02-08 at 5 18 23 PM](https://github.com/TelemetryDeck/Issues/assets/1753624/40bb2193-0a9c-4ce8-becc-48c49d694aa7)

![Screenshot 2024-02-08 at 5 16 35 PM](https://github.com/TelemetryDeck/Issues/assets/1753624/341f4418-4fbc-48bc-a620-3b8b37ef2870)

Not sure what to do. Should these populate eventually? Trying to ship this relatively quickly, but I want to be sure it works before I do.

**Comment by robertlong** [comment]
Looks like I was just impatient. All the signal types are populated now. Might be worth adding some copy to say that those signal types may take an hour or two to populate.

**Comment by winsmith** [comment]
Closing this in favour of #357
