### ISSUE TITLE
Can't dismiss webinar promotional banner

### ISSUE THREAD

**Issue by Cykelero** [TelemetryDeck/Viewer#354]
There's a new gray promotional banner at the top of every dashboard page. It takes up space and can't be dismissed. I'd really, really like to be able to hide it, please.

**Comment by jordibruin** [comment]
What browser is this in? Not seeing that here on Safari.

**Comment by Cykelero** [comment]
I use Safari as well:
![2024-02-16 18 25 38 Safari app (Interaction | Retcon | TelemetryDeck)](https://github.com/TelemetryDeck/Issues/assets/2979318/91daa380-c5b5-459e-a189-9d8291bef6b8)

(also, the banner text is on two lines, for some reason, regardless of window width or zoom level)

**Comment by winsmith** [comment]
We'll remove it soon, and the next banner will be dismissible. Thanks for your patience :)
