### ISSUE TITLE
"month" granularity seems to be broken

### ISSUE THREAD

**Issue by drewster99** [TelemetryDeck/Viewer#356]
I'm having an issue while editing an insiqht.

Insight ID: A530968F-9773-4014-9B11-ABC2AE07A433

Please describe the issue

If I set granularity to day, I see all zeroes from 12/31/2023 through 02/12/2024, with the first day of non-zero data being 02/13/2024.  This is what I expected to see.

If I set it to "week", that is also okay, showing zeros on all weeks except the week starting 02/11/2024.

However, if I set it to "month", something strange happens:
- I see zeros for the month "12/2023" -- this is correct
- I see non-zero data for the month "1/2024" -- this is WRONG -- it should be zeros
- I don't see ANY data for month "2/2024" -- this is WRONG.  All the data should be in feburary.

The data that shows as month "1/2024" SHOULD show up as 2/2024, since it's all in Feburary.

Please advise.  Thanks!

**Comment by winsmith** [comment]
Hi @drewster99, thanks for reporting this. I can't seem to reproduce that the issue right now. Could you double check and if it's still broken please? 

<img width="1979" alt="Screenshot 2024-02-26 at 12 51 55" src="https://github.com/TelemetryDeck/Issues/assets/954120/eb65f78e-9bd6-42db-a9eb-3dafcb9930a8">
