### ISSUE TITLE
Raw not displayed as single number

### ISSUE THREAD

**Issue by mpdifran** [TelemetryDeck/Viewer#362]
I have a few queries that do calculations on events to land on a single number. It would be great to have a chart type that can display this in large text with a label. Currently it's very tiny text and hard to read.

<img width="1247" alt="Screenshot 2024-02-29 at 7 07 25 PM" src="https://github.com/TelemetryDeck/Issues/assets/1365987/9191da41-58c1-43a4-b05a-f3c944c9abaa">

**Comment by winsmith** [comment]
This should already be possible. Can you try the following please:

- set granularity to "all"
- set display mode to "raw / table"

If that doesn't work, can you share the insight ID please?

**Comment by mpdifran** [comment]
I do have granularity set to `all`, and I'm using the table display mode. What I see is in the screenshot in the original post. Here's my query (not sure where to find the `Insight ID`).

```
{
  "aggregations": [
    {
      "aggregator": {
        "fieldName": "count",
        "name": "_purchase_successful_count",
        "type": "doubleSum"
      },
      "filter": {
        "dimension": "type",
        "type": "selector",
        "value": "Purchased Product"
      },
      "type": "filtered"
    },
    {
      "aggregator": {
        "fieldName": "count",
        "name": "_views_count",
        "type": "doubleSum"
      },
      "filter": {
        "dimension": "type",
        "type": "selector",
        "value": "View Picasso Pro Paywall"
      },
      "type": "filtered"
    }
  ],
  "appID": "XXXX-XXX-XXX-XXXX",
  "filter": {
    "fields": [
      {
        "dimension": "type",
        "type": "selector",
        "value": "View Picasso Pro Paywall"
      },
      {
        "dimension": "type",
        "type": "selector",
        "value": "Purchased Product"
      }
    ],
    "type": "or"
  },
  "granularity": "all",
  "postAggregations": [
    {
      "fields": [
        {
          "fieldName": "_purchase_successful_count",
          "type": "fieldAccess"
        },
        {
          "fieldName": "_views_count",
          "type": "fieldAccess"
        }
      ],
      "fn": "/",
      "name": "Conversion Rate",
      "type": "arithmetic"
    }
  ],
  "queryType": "groupBy"
}
```

**Comment by winsmith** [comment]
Thanks a lot, this'll help me find the cause way quicker!

**Comment by mpdifran** [comment]
Looks great now! Thanks for the quick turnaround!
