### ISSUE TITLE
When moving an insight the filter gets removed

### ISSUE THREAD

**Issue by carlosfernandez** [TelemetryDeck/Viewer#370]
I'm having an issue while editing an insiqht.

Insight ID: 872B803D-60FB-49D9-8813-6B5386A24CDC

Whenever I move an insight with the arrows, the filter gets removed

**Comment by winsmith** [comment]
Thanks a lot for reporting this, investigating!

**Comment by carlosfernandez** [comment]
seems fixed, thanks!
