### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by cameronmcefee** [TelemetryDeck/Viewer#371]
I'm having an issue while editing an insiqht.

Insight ID: 72DCCBF1-CBE9-4031-B906-EAB47EEAAFAF

My graphs load correctly in my dashboards, but on the page where I configure the insight, the graph fails to load with an error.

```
Error: true: Value required for key at path 'queryType'. No value associated with key CodingKeys(stringValue: "queryType", intValue: nil) ("queryType").
```

This happens on all of my graphs, regardless of type

**Comment by winsmith** [comment]
Thanks a lot, this should now be fixed!

**Comment by cameronmcefee** [comment]
Confirmed, looks resolved. Thanks 🙏
