### ISSUE TITLE
Funnel -- multiple steps with same event always shows 100%? (Insight Editor Issue)

### ISSUE THREAD

**Issue by drewster99** [TelemetryDeck/Viewer#375]
I'm having an issue while editing an insiqht.

Insight ID: 31621BD4-8B12-4048-9D4D-77605AC71EE2

I have an event called "offerWallPurchaseBegan".  I'd like to see how many times (or percentage) of people who started a purchase once, then later started it again.  So I put step 1 of my funnel event "offerWallPurchaseBegan", and then step 2 the same, "offerWallPurchaseBegan"..  However, it always shows 100%, as if a 2nd offerWallPurchaseBegan always exists after a 1st one for the user.

Am I doing something wrong?  Or do these funnels work differently than I'm expecting?

Thanks!

**Comment by winsmith** [comment]
Ah, you've found a problem with how our funnels work. They don't work time based, instead they work by creating intersections of user cohorts. So step 1 is "all users that the filter applies to" and step 2 is "all users from step 1 who also fit within the filters of step 2" and so on. So finding returning users is sadly not possible.
