### ISSUE TITLE
Funnel display enhancements: percent of previous + numerical counts

### ISSUE THREAD

**Issue by drewster99** [TelemetryDeck/Viewer#376]
Hello,

Every time I'm using funnels I wish these two features existed -- probably because, if I recall, it might be how the facebook funnel screen used to work.  Anyway, here they are:

## Percentage of prior step
(1) Add an option to show the percentage of the users at the previous funnel step, rather than the percentage of the users at the first step.

## Numerical counts
(2) Please _also_ show numerical counts - not just percentages.   Sometimes you want to know "how many people is that" and then you need to go elsewhere or temporarily edit the funnel etc to find out.

## EXAMPLES:

Say I have a f 4 step funnel, based on these events:

- firstLaunch -> engagedWithContent -> sawPaywall -> purchaseBegan

And, let's say the absolute counts that go with each step are:

- firstLaunch -- 10
- engagedWithContent -- 9
- sawPaywall -- 5
- purchaseBegan -- 2

Right now, the funnel will display:

`firstLaunch 100% -> engagedWithContent 90% -> sawPaywall 50% -> purchaseBegan 20%`

I'd like to be able to toggle that so that each step shows the percentage of the prior step, and also shows the absolute counts -- something like this:

`firstLaunch 100% (10) -> engagedWithContent 90% (9) -> sawPaywall 55.5% (5) -> purchaseBegan 40% (2)`

When you like at a funnel that way, it's MUCH easier to see where you're failing or losing people.  For example, I had analytics in a game and set up a funnel based on the user's progression through levels, and had a funnel like:

`level1Complete > level2Complete > level3Complete > level4Complete etc..`

You'd see things like:

`100% > 98% > 91% > 94% > 95% > 81% > 98% > 91%`

Looking at that progression, the 81% sticks out like a sore thumb -- its easy to see that you're really losing a lot of people at THAT STEP -- in this case, losing 19% of the people that made it to the prior step.  After that, you might also want to look at step 3 and step 8 -- the two steps that show 91%, because they are losing 9% of the users who made it to the prior step.

Continuing the same hypothetical, if the original 100% was 10,000 users, the same funnel would currently be represented with these percentages:

`100% > 98% > 89% > 84% > 80% > 65% > 63% > 58%`

The same step where we lost 19% of the people (the 81% in my preferred display format) still sticks out, because we are dropping from 80% to 65%.  But it's **really hard** to see that step 3 (89%) and the last step (58%) are both losing 9% of the users who made it to the prior step.

Numerical counts would be helpful too.  If I look at that last step, losing 9% of the users from the prior step, it would be nice to know if I'm losing 1500 users or 6.

**Comment by winsmith** [comment]
Thanks a lot for your suggestion! I've implemented them very similarly to what you describe, check it out!
