### ISSUE TITLE
Add a way to reorder insights

### ISSUE THREAD

**Issue by alexstaravoitau** [TelemetryDeck/Viewer#377]
There doesn't seem to be a way to reorder insights within the dashboard—I've tried Arc and Safari.

**Comment by winsmith** [comment]
You can use the lil left and right arrows to reorder insights :) 

<img width="830" alt="Screenshot 2024-06-26 at 15 48 36" src="https://github.com/TelemetryDeck/Issues/assets/954120/27edca39-b75d-47c3-8bea-6c241e6dee70">
