### ISSUE TITLE
Can't change "layout" to "website". Stuck on "app".

### ISSUE THREAD

**Issue by cameronmcefee** [TelemetryDeck/Viewer#378]
Hello!

I went to check my referrer graph on the Overview tab and realized it was showing "app" data instead of "website" data. It was "website" before. I went to my settings and tried to switch the "overview layout" setting, but when I select "blog of* static website", the page refreshes and the setting is still on "application related data".

Please let me know what sort of data you need from me. Is https://dashboard.telemetrydeck.com/apps/<THIS_ID>/settings safe to paste here? I assume it's fine.

\*I think there's a typo in the item

**Comment by mbuchetics** [comment]
We have the same issue.

**Comment by mbuchetics** [comment]
This is still an issue, currently it's not really usable for websites at all.

**Comment by alexsereno** [comment]
Same here!

**Comment by winsmith** [comment]
Thanks a lot for reporting this! Should be fixed now.
