### ISSUE TITLE
Login issue on app not website

### ISSUE THREAD

**Issue by markbattistella** [TelemetryDeck/Viewer#379]
I have the test flight of the iOS app and it used to be logged in fine. 

After the update to build 741 it had logged me out. Attempting to log in reports an issue with the credentials. 

However, logging in on the website it is working. 

The only thing I can see as potential issue is my email logging has a + symbol in it. 

![image](https://github.com/TelemetryDeck/Issues/assets/17962160/f8c48b5e-1216-46cc-aec5-817a497a46c7)

**Comment by betaphi** [comment]
Same here. Did you happen to find a solution, yet?

BTW, no special characters in my eMail address…

**Comment by markbattistella** [comment]
@betaphi no solution - just been using the web interface at this stage.

**Comment by winsmith** [comment]
Should be fixed now :)
