### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by tschmitz** [TelemetryDeck/Viewer#380]
I'm having an issue while editing an insiqht.

Insight ID: 141B8A21-9DF4-4D41-81F7-5D6E9B342302

When using a Top N breakdown, I'd like to be able to make a bar graph to show a frequency distribution. So instead of stacking the values into one bar, the value is plotted along the x-axis, and the number of users is plotted along the y axis.

Something like this is what I have in mind: https://ezspss.com/wp-content/uploads/2019/07/frequencydistribution6.jpg

**Comment by winsmith** [comment]
Thanks for the suggestion! Closing this as a duplicate of https://github.com/TelemetryDeck/Issues/issues/406
