### ISSUE TITLE
Top N Dimensions not available for new events

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#382]
When I'm adding new events with custom parameters I am unable to select them from the Top N Dimensions list until real life data has been received (I think).

It would be nice to be able to just paste a value in like is possible for the filter (although the problem also exists there, I first have to select another filter before I can manually edit it)

<img width="613" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/de05239d-03ef-4567-8458-fecf51fbde12">

I run into this problem for every event I make, and it takes a lot of extra steps just to add one as a result.

**Comment by winsmith** [comment]
Thanks, this is a caching issue that is now fixed
