### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by macdevnet** [TelemetryDeck/Viewer#390]
I'm having an issue while editing an insiqht.

Insight ID: B759EC54-6339-4F28-8D04-91E99EDC516F

Please describe the issue

Chart reporting server error. 
![CleanShot 2024-04-29 at 12 26 06@2x](https://github.com/TelemetryDeck/Issues/assets/5823681/023d59fa-6496-413b-b8b6-e71f8d3f244c)

**Comment by winsmith** [comment]
Thanks for reporting this! This is a server problem and we're working on it
