### ISSUE TITLE
Add weekday to chart hover boxes that show the date

### ISSUE THREAD

**Issue by DivineDominion** [TelemetryDeck/Viewer#391]
![2024-05-07 21-47-54 Arc - TelemetryDeck@2x](https://github.com/TelemetryDeck/Issues/assets/59080/d910cd63-75cd-4009-bc66-1a430cfb0b97)

Would be cool if TD shows the day of the week in graphs on the "Your Apps" overview. The date is shown on hover, but not whether it is Monday, Thursday or Sunday.

**Comment by jordibruin** [comment]
Yes, been wanting this for a loong time too!

**Comment by winsmith** [comment]
Done :D~

**Comment by DivineDominion** [comment]
Nice! 🙌
