### ISSUE TITLE
Missing signals/users

### ISSUE THREAD

**Issue by alexstaravoitau** [TelemetryDeck/Viewer#393]
Looks like a decent chunk of signals (users?) is missing starting from 17/5—if I were to guess looks like numbers are roughly half of what they should be.

**Comment by KlemensStrasser** [comment]
Again today, last signals came in at 01:00 PM.

**Comment by finebel** [comment]
I have just set up a new app and haven't seen any signals so far while testing the app via the iOS simulator (even though I enabled "Test mode" in the Dashboard). Signals were sent ~1 hour ago.

**Comment by alexstaravoitau** [comment]
I'm also sending signals with the iOS SDK btw—and it's still very erratic.

**Comment by winsmith** [comment]
Should be all good now. Apologies for the inconvenience. We're moving to a more reliable server technology soon (away from Kubernetes and towards VMs)
