### ISSUE TITLE
App versions default widget not showing latest versions

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#395]
<img width="408" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/0c3631af-c7f7-47bf-a3fb-93d162dded3f">

It just shows very old versions for me.

**Comment by winsmith** [comment]
Might be that you have a lot of versions and the widget just shows the top N versions where N is a too low number. Investigating!

**Comment by jordibruin** [comment]
@winsmith no it seems to be showing very old versions, none of my recent ones showing up (Im on 8.10 now)

<img width="196" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/f312f449-334d-4dd3-9608-2164463b7b1a">

**Comment by winsmith** [comment]
As I suspected: the query for this chart showed you the 20 lowest versions in your dataset. I'll update it to show the e.g. 30 newest versions instead.
