### ISSUE TITLE
Newly created insights appear in the second spot and not the bottom of the list

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#396]
When making a new insight they appear on the second spot. I then have to click the right arrow 10+ times to move it to the bottom, each time waiting for the page to reload. Defaulting it to the last slot makes more sense.

**Comment by Jeehut** [comment]
@jordibruin I couldn't reproduce this problem, the behavior both on the production website and also on my dev machine was exactly what you would expect.

I created new insights by clicking the "Create new insight" button at the end of the insights list and named them "1st", "2nd", "3rd", and "4th". After creation I was automatically routed to the insight detail page. When I pressed the back button, they always appeared at the end of the list. See here:
<img width="1914" alt="Bildschirmfoto 2024-05-31 um 20 42 01" src="https://github.com/TelemetryDeck/Issues/assets/6942160/0a3c8e6e-95b0-414b-9934-5744cb778809">

Is this still happening to you? If yes, could you provide more details about your environment? Maybe it's only happening in specific situations. I tested in latest Safari on latest macOS.

**Comment by jordibruin** [comment]
Just tested again and seems to be fixed, thanks!
