### ISSUE TITLE
Broken Link in Purchase Tab

### ISSUE THREAD

**Issue by winsmith** [TelemetryDeck/Viewer#397]
![Image](https://github.com/TelemetryDeck/Issues/assets/954120/60e23027-6bb6-4874-84bf-d0af2ab26a0d)

**Comment by Jeehut** [comment]
Oh, let me check…

**Comment by Jeehut** [comment]
This should be fixed by now by merging https://github.com/TelemetryDeck/docs/pull/82. Closing.
