### ISSUE TITLE
Seeing a lot of events with empty payload (this is from 3 days)

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#398]
<img width="621" alt="image" src="https://github.com/TelemetryDeck/Issues/assets/170948/7453aa02-d955-4f5f-80b7-a980a35556a2">

**Comment by winsmith** [comment]
Hi, thanks for submitting! Can you check if only signals with a "submittedIgnoreSegment" are being included in the query please? If yes, can you send me an insight ID or the query please?

**Comment by Jeehut** [comment]
@jordibruin Inspired by this issue, we thought it would be a good UX improvement to make it as easy as possible to hide empty values in Top-N insights. So now, in any Top-N insight that has no filters applied yet (e.g. any new insight), you'll find a "Add filter to ignore empty values" button to quickly get rid of those empty values. It works like this:

https://github.com/TelemetryDeck/web/assets/6942160/e82d652c-1833-43eb-a68d-0e6861641a8a

I'm not sure if this resolves your issue. If it does, feel free to close this. I hope you like it in any case!
