### ISSUE TITLE
Insight Editor can't delete insight

### ISSUE THREAD

**Issue by funkinspektor** [TelemetryDeck/Viewer#404]
I'm having an issue while editing an insiqht.

Insight ID: EC081FBE-F73A-4FC8-A366-B8BB0286512E

Please describe the issue: 
I can't delete the insight. The button doesn't do anything.

**Comment by winsmith** [comment]
Thanks for reporting, we'll take a look

**Comment by winsmith** [comment]
I can't reproduce the issue
