### ISSUE TITLE
Double "Are you sure you want to delete this insight" alert

### ISSUE THREAD

**Issue by jordibruin** [TelemetryDeck/Viewer#407]
https://github.com/TelemetryDeck/Issues/assets/170948/0e30fa68-ca64-4875-9099-8710701cd24e

Shows up twice

**Comment by Jeehut** [comment]
@winsmith I just tested this (as it's been 2 months since this was reported) and I couldn't reproduce, neither in Safari nor in Arc (I'm on macOS Sonoma). Could this have been resolved (e.g. by some dependency update)? Does it happen for you?

**Comment by jordibruin** [comment]
Solved now
