### ISSUE TITLE
Funnels only display first step

### ISSUE THREAD

**Issue by palmin** [TelemetryDeck/Viewer#420]
I'm having an issue while editing an insiqht.

Insight ID: 0DF457B4-7288-446C-9272-D533BAFF1587

Please describe the issue

Earlier today my funnels started acting weird and it looks like only the first step is shown correctly.

The easiest way to replicate this is by making a funnel where both steps require the same signal type.
I would expect the second step to be 100% of the first step but isn't.

**Comment by palmin** [comment]
Now it works again. 😊

**Comment by palmin** [comment]
It worked for a very short time and then returned to not working. 
Attached a video illustrating the bug.

https://github.com/user-attachments/assets/95b67e74-666c-43ef-911a-c4df857f508a

**Comment by alexstaravoitau** [comment]
Same here: all funnel charts are broken as of a couple of days ago—i.e. they now only display the 100% of users in the first step, and nothing for further steps.

**Comment by ramzesenok** [comment]
Same here https://github.com/TelemetryDeck/Issues/issues/422

**Comment by liri2006** [comment]
Same here. There are bunch of same type errors in Developer Console:
![image](https://github.com/user-attachments/assets/4d6472a4-7fbb-4287-b25b-eeb2a2beee6a)

**Comment by liri2006** [comment]
@winsmith Hi, any ETA for the fix? ;)

**Comment by winsmith** [comment]
@liri2006  No but I'm on it

**Comment by winsmith** [comment]
Nevermind I'm dumb. Fix incoming...

**Comment by elsa17z** [comment]
> Nevermind I'm dumb. Fix incoming...

That's such a mood, exactly like us over here lol

**Comment by marcpalmer** [comment]
@winsmith am I being dumb / is there a data backlog? If not, why don't these numbers make sense to me? Surely it should show 810 -> 695?

![Screenshot 2024-07-26 at 15 11 29](https://github.com/user-attachments/assets/d454ef90-4180-45d7-962a-72aebbb918ca)
![Screenshot 2024-07-26 at 15 11 52](https://github.com/user-attachments/assets/27708d2d-f438-42a5-9e0f-19a88b60fbd5)

**Comment by marcpalmer** [comment]
Bumping this... am I just being dumb — is it showing unique users rather than signals in the funnel or something @winsmith ? Why would the numbers differ like this? Pushing on this because if I am misunderstanding this, it probably needs a little UX love to make it clearer too. If I am not misunderstanding it, I don't understand how to relate to this info!

**Comment by winsmith** [comment]
Hi @marcpalmer, your assumption is correct: funnels show numbers of unique users, not numbers of signals. We recently updated the wording underneath the bars in funnel charts to hopefully make this clearer.
