### ISSUE TITLE
Funnel seems broken

### ISSUE THREAD

**Issue by ramzesenok** [TelemetryDeck/Viewer#422]
I'm having an issue while editing an insiqht.

Insight ID: 47AB8E40-4DBE-417A-8068-AFDB0A8E4779

I've added multiple steps into Funnel chart but it only displays the first step with 100% users. I'm sure there are signals for other steps, other line charts show them

**Comment by winsmith** [comment]
Thanks for reporting, this is 100% an issue. I'll close this ticket in favour of #420
