### ISSUE TITLE
Insight Editor Issue — I'm too stupid to understand the funnel UI?

### ISSUE THREAD

**Issue by marcpalmer** [TelemetryDeck/Viewer#428]
I'm having an issue while editing an insiqht.

Insight ID: 90337E91-BC36-4032-88AC-71D62F9C5F94

Hi Daniel,

I'm trying to set up a trivial funnel — to see the number of people starting a session, who then also import an image into my app.

When I add the TD "session started" event as the first funnel step and my import image signal as the second step, I get only one column.

My dumb assumption is that I would see the total sessions first, then the reduced amount of people that make it through to the import image step. Is this not how it works? If not... why, and maybe it needs explaining in the UI more for dumbasses like me :)

Cheers

**Comment by marcpalmer** [comment]
![Screenshot 2024-07-26 at 11 27 22](https://github.com/user-attachments/assets/6f71d5f8-000e-4948-84e2-a1c262430c14)
![Screenshot 2024-07-26 at 11 27 14](https://github.com/user-attachments/assets/ef47f59a-5a59-4883-b3fe-7693e81e1330)

This just doesn't make any sense to me vs. the signals received. Should't it be 543 in Start, and 432 in an Import column?

**Comment by liri2006** [comment]
@marcpalmer There is an issue for this here - https://github.com/TelemetryDeck/Issues/issues/420.
We've been waiting for a fix for quite a few days now.
