### ISSUE TITLE
Insight Editor Issue

### ISSUE THREAD

**Issue by benrudhart** [TelemetryDeck/Viewer#430]
I'm having an issue while editing an insiqht.

Insight ID: 8F8D0238-0C6A-4D37-A517-1B89D7F7C3C8

Please describe the issue:
When using the "donut chart" type for a property of a signal that is only sent once (with true or false) I also see a lot of "none" values. I guess that's caused by other signals, that don't include that property at all.
I'm not interested in these when looking at the chart. 
Is there a way to use the donut chart and make it show a percentage of the values only for the signals that do include the property, i.e. ignore the "none" values from signals that don't include the property?

**Comment by winsmith** [comment]
<img width="381" alt="Screenshot 2024-08-19 at 14 09 17" src="https://github.com/user-attachments/assets/3bf29372-e2fb-46fb-9778-673c512ecaf3">

We just added a button that creates an "ignore none values" filter for you!
