### ISSUE TITLE
"No results found for segments" error

### ISSUE THREAD

**Issue by DivineDominion** [TelemetryDeck/Viewer#432]
I changed the dashboard range to "Current Year" and got errors; I tried 90d and also got errors. Some went away on the dashboard, but clicking any website property produces more:

```
Error: Abort.400: No results found for segments[[SegmentDescriptor{interval=2024-06-06T00:00:00.000Z/2024-06-07T00:00:00.000Z, version='2024-07-30T19:51:09.273Z', partitionNumber=0}, SegmentDescriptor{interval=2024-06-06T00:00:00.000Z/2024-06-07T00:00:00.000Z, version='2024-07-30T19:51:09.273Z', partitionNumber=1}]]: undefined
```

Sample:
![2024-08-07 09-40-54 Arc - christiantietze de  TelemetryDeck@2x](https://github.com/user-attachments/assets/ece7eab7-6c92-4bfe-9549-e9790f8870e8)

**Comment by winsmith** [comment]
Thanks for reporting this. The issue has been resolved!
